b = input("digite algo: ")
print('o tipo digitado é: ',type(b))
print('-=-'*12)
print('só tem espaço: ',b.isspace())
print('-=-'*12)
print('é um numero: ? ',b.isnumeric())
print('-=-'*12)
print('é alfabetico? : ', b.isalpha())
print('-=-'*12)
print('é alfanumerico? :', b.isalnum())
print('-=-'*12)
print('esta em MAIUSCULA: ?',b.isupper())
print('-=-'*12)
print('esta em minuscula? ', b.islower())
print('-=-'*12)
print('esta capitadalizo? ', b.istitle())
